version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    volumes:
      - .:/var/www
    environment:
      XDEBUG_MODE: "debug,coverage"
      XDEBUG_CONFIG: "remote_host=host.docker.internal"